// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSerial(arg1:string):Promise<string>;

export function GetPorts():Promise<Array<string>>;

export function HideWindow():Promise<void>;

export function SendCommand(arg1:string):Promise<string>;

export function SetAutoMode(arg1:boolean,arg2:string):Promise<string>;
