// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSerial(arg1) {
  return window['go']['main']['App']['ConnectSerial'](arg1);
}

export function GetPorts() {
  return window['go']['main']['App']['GetPorts']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}

export function SetAutoMode(arg1, arg2) {
  return window['go']['main']['App']['SetAutoMode'](arg1, arg2);
}
